# Generated by Django 5.0.3 on 2024-04-02 17:46

import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.URLField(), size=None),
        ),
    ]
